stages:
  - sit
  - uat
  - prod
  - master
test:
  stage: test
  only:
    - test
  tags:
    - test
  script:
    - echo "start test"

master:
  stage: master
  tags:
    - master
  only:
    - master
  script:
    - echo "start master"