stages:
  - test
  - dev
  - prod
test:
  stage: test
  only:
    - test
  tags:
    - test
  script:
    - echo "start test"

dev:
  stage: dev
  tags:
    - dev
  only:
    - master
  script:
    - echo "start dev"