services:
  - name: docker:18.09.7-dind
stages:
  - sit
  - uat
  - prod
  - master
sit:
  stage: sit
  only:
    - sit
  tags:
    - sit
  script:
    - echo "start sit"

master:
  stage: master
  tags:
    - master
  only:
    - master
  script:
    - echo "start master"