stages:
  - sit
  - uat
  - prod
  - master
sit:
  stage: sit
  only:
    - sit
  tags:
    - sit
  script:
    - git clone http://192.168.204.130/root/railsDemo.git
    - docker-compose up

master:
  stage: master
  tags:
    - master
  only:
    - master
  script:
    - git clone http://192.168.204.130/root/railsDemo.git
    - docker-compose up